### ISSUE TITLE
Fix styling for various subpages

### ISSUE THREAD

**Issue by novedevo** [novedevo/notable#102]
Relevant to https://github.com/novedevo/notable/issues/17, right now the admin console looks like this: 
![image](https://user-images.githubusercontent.com/20878868/181071171-54b23a42-2343-4fd9-b694-9c99f119f059.png)
, which is pretty unreadable per WCAG guidelines

**Comment by novedevo** [comment]
Also applies to the various presentation subpages
![image](https://user-images.githubusercontent.com/20878868/181073077-4cd3bdc1-ff4a-4fa3-b134-0e5cb648123f.png)
![image](https://user-images.githubusercontent.com/20878868/181073083-5003e3e5-28f3-4eb4-93c6-4afdb5cab07d.png)
![image](https://user-images.githubusercontent.com/20878868/181073145-9390603d-8ca0-4b69-b54b-391175400dcb.png)
![image](https://user-images.githubusercontent.com/20878868/181073242-da4a31ac-0ef7-4db1-85d5-c32b79987748.png)

**Comment by novedevo** [comment]
the dashboard button is floating! very cute
![image](https://user-images.githubusercontent.com/20878868/181073398-58ca8c79-f3f3-451d-b0fe-c177ddbb354b.png)

**Comment by t-chu4** [comment]
Font colour switched to white against dark backgrounds. Text fields and DataGrid backgrounds set to white. "Return to Dashboard" button will eventually be replaced by the new sidebar, no changes made.
