### ISSUE TITLE
various sidebar-content hiding issues

### ISSUE THREAD

**Issue by novedevo** [novedevo/notable#126]
![image](https://user-images.githubusercontent.com/20878868/181340928-4ef5854c-69df-46ec-a98d-6f23cc2f725c.png)

**Comment by novedevo** [comment]
it's also too narrow for its content
![image](https://user-images.githubusercontent.com/20878868/181364480-5b8b9399-a606-4ffc-8589-670c3f5e1f6a.png)

**Comment by novedevo** [comment]
it also is hidden by presentations in the myNotes page
![image](https://user-images.githubusercontent.com/20878868/181367855-1b40a6fe-b823-43e5-8699-2d4412c362c1.png)

**Comment by t-chu4** [comment]
Above issues have been fixed. So long as people don't resize their browser windows to be a third of their screen width, which isn't viable even with scaling :P
