### ISSUE TITLE
Unify styling

### ISSUE THREAD

**Issue by novedevo** [novedevo/notable#17]
CSS should be consistent across login/logout/register, admin console, presenter view, pdf view, notetaking, etc. Using Bootstrap is probably a good idea; they do a lot for us. We can set accent colours and customize their behaviour quite a bit with css variables and stuff.

**Comment by novedevo** [comment]
Now that we're using React, we can use https://mui.com/, which is an easy-to-use library with a ton of prestyled components for us to use, making our app feel unified and cohesive (and pretty!)

**Comment by jamie-chin** [comment]
Bobby wants us to make it look like a real app now so this should probably be higher priority on our list :)

**Comment by t-chu4** [comment]
style has been matched for various subpages, still open for future tweaks but considered presentable as is
