### ISSUE TITLE
prefer class over id for css selection when multiple elements need the same style

### ISSUE THREAD

**Issue by novedevo** [novedevo/notable#182]
https://css-tricks.com/the-difference-between-id-and-class/

**Comment by t-chu4** [comment]
![image](https://user-images.githubusercontent.com/105568393/182315162-004a3095-609f-4052-b0d2-157850f52e77.png)

does not appear to be an option

**Comment by novedevo** [comment]
use `className` instead of `class` because `class` is a reserved token in js
