### ISSUE TITLE
video and note panel are offset, should be vertically aligned with each other

### ISSUE THREAD

**Issue by novedevo** [novedevo/notable#183]
![image](https://user-images.githubusercontent.com/20878868/182275105-165a6fb0-a3d2-4484-8012-a74d4cb9060a.png)

**Comment by t-chu4** [comment]
Replaced with a different kind of offset. Alignment changed so middle of video meets with middle of feed (in most cases). They weren't the same height before, adapted for spacing.
![image](https://user-images.githubusercontent.com/105568393/182555704-27de6f25-9d26-4fd4-9f1f-abf8e73cc5dc.png)
