### ISSUE TITLE
schedule presentation button overlaps with the rest of the screen

### ISSUE THREAD

**Issue by novedevo** [novedevo/notable#218]
![image](https://user-images.githubusercontent.com/20878868/182740964-65154b18-c417-465d-a9f1-386d8e50e43c.png)

**Comment by novedevo** [comment]
actually, the whole page is a little misaligned:
![image](https://user-images.githubusercontent.com/20878868/182741182-df5334b9-32b3-4232-b7c4-b5ccb1d6e057.png)

**Comment by novedevo** [comment]
this only happens on scaling values of over 100%, but that is most laptops, so this is an issue

**Comment by novedevo** [comment]
it also happens on the scheduling page, and maybe others idk
![image](https://user-images.githubusercontent.com/20878868/182744459-f64aabe7-22d8-40ec-be26-718ffbdadc0d.png)

**Comment by daantosaurus** [comment]
is it viable to just add tom/bottom paddings? or would this mess things up on larger monitors
