### ISSUE TITLE
"past presentations" screen for the presenter so they can upload a youtube video to sync the notes

### ISSUE THREAD

**Issue by jamie-chin** [novedevo/notable#75]
When a presentation is over, remove it from the upcoming presentations screen. We might have to put the presentation somewhere else though, like a "past presentations" screen for the presenter so they can upload a youtube video to sync the notes (#73) .
The presentations need an end time to be set by the presenter to be able to do this. (Or some other solution that marks a presentation as finished, but an end time would make it the most seamless.)

**Comment by 33opo** [comment]
this one has mostly been completed, just no way of currently viewing past presentations unless you have notes in them
