### ISSUE TITLE
Some kind of feedback when generate note button is pressed

### ISSUE THREAD

**Issue by jamie-chin** [novedevo/notable#79]
---------------------lower priority---------------------
Try to avoid making an alert for this because those should usually be to warn a user that they did something wrong and is a bit awkward (workflow wise) for the user to have to press 'ok' on a popup once they made a presentation.
Can either just say "presentation created!" and redirect user to the presentation page
or
Show "presentation created with ID: xyz" on the page like under the save presentation button or something

**Comment by 33opo** [comment]
Looks like this one has been completed by someone
